/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class adds_TestNative */

#ifndef _Included_adds_TestNative
#define _Included_adds_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     adds_TestNative
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_adds_TestNative_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
