/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dictlib_DictNative */

#ifndef _Included_dictlib_DictNative
#define _Included_dictlib_DictNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dictlib_DictNative
 * Method:    readIndex
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dictlib_DictNative_readIndex
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dictlib_DictNative
 * Method:    decodeArticle
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dictlib_DictNative_decodeArticle
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
