/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dictlib_DictNative */

#ifndef _Included_dictlib_DictNative
#define _Included_dictlib_DictNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dictlib_DictNative
 * Method:    readIndex
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dictlib_DictNative_readIndex
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dictlib_DictNative
 * Method:    decodeArticle
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dictlib_DictNative_decodeArticle
  (JNIEnv *, jobject, jint);

/*
 * Class:     dictlib_DictNative
 * Method:    getDictName
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_dictlib_DictNative_getDictName
  (JNIEnv *, jobject);

/*
 * Class:     dictlib_DictNative
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dictlib_DictNative_clear
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
