/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class marisa_AddProcessNative */

#ifndef _Included_marisa_AddProcessNative
#define _Included_marisa_AddProcessNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     marisa_AddProcessNative
 * Method:    buildTrie
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_marisa_AddProcessNative_buildTrie
  (JNIEnv *, jobject, jstring);

/*
 * Class:     marisa_AddProcessNative
 * Method:    linkData
 * Signature: (Lmarisa/KeysetNative;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_marisa_AddProcessNative_linkData
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
